services:
  dms-mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: dms-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=dmS1021<zh>
    - MYSQL_DATABASE=dms
    image: mysql:5.7
    ports:
    - 9536:3306
    restart: always
    volumes:
    - dms-mysql:/var/lib/mysql
version: '2.4'
volumes:
  dms-mysql:
    name: dms-mysql
